version: '3.9'

services:
  database:
    image: postgres:17.0-alpine
    container_name: database
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - database_storage:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: admin
      POSTGRES_DB: backend_database
      PGDATA: /var/lib/postgresql/data/pgdata
      
  cache:
    image: redis:7.4.1-alpine
    container_name: cache
    restart: unless-stopped
    ports:
      - "6379:6379"
      
volumes:
  database_storage: