version: '3.9'

services:
  karpenko.university.backend:
    container_name: karpenko.university.backend
    build:
      context: .
      dockerfile: Karpenko.University.Backend.API/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    networks:
      - internal_net
      
networks:
  internal_net:
    driver: bridge
  external_net:
    driver: bridge